module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
};
[ { constant: true,
  inputs: [ [Object] ],
  name: 'ratingsReceived',
  outputs: [ [Object] ],
  payable: false,
  stateMutability: 'view',
  type: 'function' },
{ constant: true,
  inputs: [ [Object] ],
  name: 'movieList',
  outputs: [ [Object] ],
  payable: false,
  stateMutability: 'view',
  type: 'function' },
{ inputs: [ [Object] ],
  payable: false,
  stateMutability: 'nonpayable',
  type: 'constructor' },
{ constant: true,
  inputs: [ [Object] ],
  name: 'totalVotesFor',
  outputs: [ [Object] ],
  payable: false,
  stateMutability: 'view',
  type: 'function' },
{ constant: false,
  inputs: [ [Object] ],
  name: 'voteForMovie',
  outputs: [],
  payable: false,
  stateMutability: 'nonpayable',
  type: 'function' } ]
